# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            DISCO
tagline:          'Distributed Computing as a Service'
description:      '...Distributed Computing in the Cloud â€“ automated'
url:              http://icclab.github.io/disco
baseurl:          https://icclab.github.io/disco/

jekyll-paginate:         5

github:
  repodashboard:         https://github.com/icclab/disco-dashboard
  repobackend:           https://github.com/icclab/disco

